### ISSUE TITLE
Arch package requires semantic_version

### ISSUE THREAD

**Issue by ChasNelson1990** [etesync/etebase-py#21]
Hi,

Just tried toinstall etesync-dav on a new laptop using pikaur on Arch Linux (`pikaur -Syu etesync-dav`).

I got a `ModuleNotFoundError: No module named 'semantic_version'` error during the build of the python-etebase AUR package.

I have python-semantic-version installed globally but I guess it's not in the build env?

I presume it just needs to be added as a dependency?

P.S. Sorry for the lack of traceback, said new laptop doesn't have a GUI yet.

**Comment by tasn** [comment]
It's needed by python-setuptools-rust which has it as a dep: https://aur.archlinux.org/packages/python-setuptools-rust/
Which is why I guess you have it installed. I'm not sure why it's not finding it for you. It works for people and it works for me.
Try running Python and then: `import semantic_version`, does that work?

**Comment by ChasNelson1990** [comment]
Okay, my bad. This looks like a python 3.9 issue - my upgrade to 3.9 means the system thinks I have all these packages but they're actually installed in the python 3.8 libs. Solved now, thanks.
